name: spatial-viewer
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.20=py310h19b6747_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - icu=78.2=h38cb7af_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - krb5=1.21.3=h237132a_0
  - libcxx=21.1.8=h55c6f16_2
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=hcf2aa1b_0
  - liblzma=5.8.2=h8088a28_0
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.51.2=h1ae2325_0
  - libzlib=1.3.1=h8359307_2
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.1=hd24854e_1
  - packaging=26.0=pyhcf101f3_0
  - parso=0.8.6=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=26.0.1=pyh8b19718_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.2=py310haea493c_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.19=hcd7f573_3_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=8_cp310
  - pyzmq=27.1.0=py310hc4a7dca_0
  - readline=8.3=h46df422_0
  - setuptools=82.0.0=pyh332efcf_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=h010d191_3
  - tornado=6.5.4=py310hfe3a0ae_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.6.0=pyhd8ed1ab_0
  - wheel=0.46.3=pyhd8ed1ab_0
  - zeromq=4.3.5=h888dc83_9
  - pip:
      - alabaster==1.0.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - app-model==0.4.0
      - appdirs==1.4.4
      - asciitree==0.3.3
      - attrs==25.4.0
      - babel==2.18.0
      - build==1.4.0
      - cachey==0.2.1
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - dask==2026.1.2
      - docstring-parser==0.17.0
      - docutils==0.21.2
      - fasteners==0.20
      - flexcache==0.3
      - flexparser==0.4
      - freetype-py==2.5.1
      - fsspec==2026.2.0
      - heapdict==1.0.1
      - hsluv==5.0.4
      - idna==3.11
      - imagecodecs==2025.3.30
      - imageio==2.37.2
      - imagesize==1.4.1
      - importlib-metadata==8.7.1
      - in-n-out==0.2.1
      - ipykernel==6.31.0
      - ipython-pygments-lexers==1.1.1
      - jinja2==3.1.6
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - locket==1.0.0
      - magicgui==0.10.1
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - napari==0.6.6
      - napari-console==0.1.4
      - napari-plugin-engine==0.2.1
      - napari-svg==0.2.1
      - nd2==0.11.2
      - networkx==3.4.2
      - npe2==0.8.1
      - numcodecs==0.13.1
      - numpy==2.2.6
      - numpydoc==1.10.0
      - ome-types==0.6.3
      - pandas==2.3.3
      - partd==1.4.2
      - pillow==12.1.1
      - pint==0.24.4
      - pooch==1.9.0
      - psygnal==0.15.1
      - pyconify==0.2.1
      - pydantic==2.12.5
      - pydantic-compat==0.1.2
      - pydantic-core==2.41.5
      - pydantic-extra-types==2.11.0
      - pyopengl==3.1.10
      - pyproject-hooks==1.2.0
      - pyqt6==6.10.2
      - pyqt6-qt6==6.10.2
      - pyqt6-sip==13.11.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - qtconsole==5.7.1
      - qtpy==2.4.3
      - referencing==0.37.0
      - requests==2.32.5
      - resource-backed-dask-array==0.1.0
      - rich==14.3.2
      - rpds-py==0.30.0
      - scikit-image==0.25.2
      - scipy==1.15.3
      - shellingham==1.5.4
      - snowballstemmer==3.0.1
      - sphinx==8.1.3
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - superqt==0.7.8
      - tifffile==2025.5.10
      - tomli==2.4.0
      - tomli-w==1.2.0
      - toolz==1.1.0
      - tqdm==4.67.3
      - typer==0.21.2
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.3
      - vispy==0.15.2
      - wrapt==2.1.1
      - xsdata==26.1
      - zarr==2.18.3
      - zipp==3.23.0
prefix: /opt/anaconda3/envs/spatial-viewer
